backend:
  name: git-gateway
media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"
publish_mode: editorial_workflow

collections:
  - name: "guideline_page"
    label: "Guideline Page"
    folder: "src/guidelines"
    create: true
    slug: "{{slug}}"
    preview_path: "/guidelines/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/md-layout.njk"}
      - {label: "Body", name: "body", widget: "markdown"}